### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by ghost** [AlchemicRaker/alchemy65#13]
how to install this so that cc65 works?

**Comment by DoctorMikeReddy** [comment]
I guess you can close this one (and the other) as the user, nes-girl aka rainbowsgirl, has either been removed by GitHub (or self-deleted her account) after being reported for abuse and hate speech. She emailed me to ask for help with Alchemy65. Like an idiot I gave up two hours of my Saturday morning to write a tutorial for installing it and a template repo to check it all worked. After this she didn't thank me but kept asking more and more queries until I explained it was too much. At which point she wrote abusive emails and issues on the repo. I blocked and reported her to GitHub, and blocked her email to my account. In response, yesterday she created a new email account to tell me (possibly not true) that she'd posted my contact details as a "pedophile" (sic) to the dark web. This has now need referred to the local Police. 

No good deed goes unpunished

**Comment by AlchemicRaker** [comment]
That's really messed up, man! I'm sorry that happened to you. I'll close these issues and be wary going forward. Thanks for the heads up.
